import type { SkillDefinition } from "./types.js";

export const CURRICULUM_VERSION = "rebuild-block4-phase3-minor-scales" as const;

const phase1Shared = {
  phase: 1 as const,
  contentKind: "lesson" as const,
  assessed: true,
  blocksPhaseCompletion: true,
  foundationality: 5 as const,
  automaticRecall: 5 as const,
  reviewPriority: 5 as const,
  longTermRecurrence: 5 as const,
  prerequisiteImportance: 5 as const,
};

const phase2Shared = {
  phase: 2 as const,
  contentKind: "lesson" as const,
  assessed: true,
  blocksPhaseCompletion: true,
  foundationality: 5 as const,
  automaticRecall: 5 as const,
  reviewPriority: 5 as const,
  longTermRecurrence: 5 as const,
  prerequisiteImportance: 5 as const,
};

const phase3Shared = {
  phase: 3 as const,
  contentKind: "lesson" as const,
  assessed: true,
  blocksPhaseCompletion: true,
  foundationality: 5 as const,
  automaticRecall: 5 as const,
  reviewPriority: 5 as const,
  longTermRecurrence: 5 as const,
  prerequisiteImportance: 5 as const,
};

export const SKILLS: readonly SkillDefinition[] = Object.freeze([
  {
    ...phase1Shared,
    id: "intervals.lesson-1-unison-octave",
    title: "Perfect Unison & Perfect Octave",
    prerequisites: [],
    evidence: ["construct", "identify"],
    tags: ["interval", "perfect", "P1", "P8", "automatic-recall"],
    conceptualUnderstanding: 3,
    acquisitionRoundSize: 30,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-2-perfect-fifth",
    title: "Perfect 5th",
    prerequisites: ["intervals.lesson-1-unison-octave"],
    evidence: ["construct", "identify"],
    tags: ["interval", "perfect", "P5", "automatic-recall", "cumulative"],
    conceptualUnderstanding: 3,
    acquisitionRoundSize: 36,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-3-perfect-fourth",
    title: "Perfect 4th",
    prerequisites: ["intervals.lesson-2-perfect-fifth"],
    evidence: ["construct", "identify", "transform"],
    tags: ["interval", "perfect", "P4", "P5", "inversion", "automatic-recall", "concept"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 36,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-4-thirds",
    title: "Major 3rd & Minor 3rd",
    prerequisites: ["intervals.lesson-3-perfect-fourth"],
    evidence: ["construct", "identify", "diagnose"],
    tags: ["interval", "major-minor", "M3", "m3", "automatic-recall", "cumulative"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 40,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-5-sixths",
    title: "Major 6th & Minor 6th",
    prerequisites: ["intervals.lesson-4-thirds"],
    evidence: ["construct", "identify", "transform", "diagnose"],
    tags: ["interval", "major-minor", "M6", "m6", "M3", "m3", "inversion", "automatic-recall", "cumulative"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 40,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-6-seconds",
    title: "Major 2nd & Minor 2nd",
    prerequisites: ["intervals.lesson-5-sixths"],
    evidence: ["construct", "identify", "diagnose"],
    tags: ["interval", "major-minor", "M2", "m2", "automatic-recall", "cumulative"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 40,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-7-sevenths",
    title: "Major 7th & Minor 7th",
    prerequisites: ["intervals.lesson-6-seconds"],
    evidence: ["construct", "identify", "transform", "diagnose"],
    tags: ["interval", "major-minor", "M7", "m7", "M2", "m2", "inversion", "automatic-recall", "cumulative"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 40,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-8-tritone",
    title: "Tritone: Augmented 4th / Diminished 5th",
    prerequisites: ["intervals.lesson-7-sevenths"],
    evidence: ["construct", "identify", "diagnose", "transform"],
    tags: ["interval", "tritone", "A4", "d5", "enharmonic", "spelling", "automatic-recall", "concept"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 40,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-9-inversion-capstone",
    title: "Inversion Rule Capstone",
    prerequisites: ["intervals.lesson-8-tritone"],
    evidence: ["transform", "construct", "identify", "apply"],
    tags: ["interval", "inversion", "rule-of-9", "quality-inversion", "automatic-recall", "concept", "cumulative"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 36,
  },
  {
    ...phase1Shared,
    id: "intervals.lesson-10-cumulative",
    title: "Cumulative Drilling",
    prerequisites: ["intervals.lesson-9-inversion-capstone"],
    evidence: ["construct", "identify", "transform", "diagnose", "apply"],
    tags: ["interval", "cumulative", "automaticity", "spelling", "inversion", "mixed-practice"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 60,
  },

  {
    ...phase2Shared,
    id: "major-scales.lesson-1-formula",
    title: "Major Scale Formula",
    prerequisites: ["intervals.lesson-10-cumulative"],
    evidence: ["identify", "construct", "apply"],
    tags: ["major-scale", "formula", "WWHWWWH", "whole-step", "half-step", "interval-connection"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 36,
  },
  {
    ...phase2Shared,
    id: "major-scales.lesson-2-degree-names",
    title: "Scale Degree Names",
    prerequisites: ["major-scales.lesson-1-formula"],
    evidence: ["identify", "translate", "apply"],
    tags: ["major-scale", "scale-degree", "tonic", "dominant", "leading-tone", "automatic-recall"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 42,
  },
  {
    ...phase2Shared,
    id: "major-scales.lesson-3-build-all-roots",
    title: "Building the Major Scale From Every Root",
    prerequisites: ["major-scales.lesson-2-degree-names"],
    evidence: ["construct", "translate", "diagnose", "apply"],
    tags: ["major-scale", "12-pitch-classes", "spelling", "one-letter-each", "enharmonic", "construction"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 48,
  },
  {
    ...phase2Shared,
    id: "major-scales.lesson-4-instant-recall",
    title: "Major Scale Instant Recall Drill",
    prerequisites: ["major-scales.lesson-3-build-all-roots"],
    evidence: ["construct", "identify", "apply"],
    tags: ["major-scale", "automaticity", "12-pitch-classes", "distributed-retrieval", "spelling", "mixed-practice"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 60,
  },

  {
    ...phase3Shared,
    id: "minor-scales.lesson-1-natural-formula",
    title: "Natural Minor Formula",
    prerequisites: ["major-scales.lesson-4-instant-recall"],
    evidence: ["identify", "construct", "apply"],
    tags: ["minor-scale", "natural-minor", "formula", "WHWWHWW", "interval-connection"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 36,
  },
  {
    ...phase3Shared,
    id: "minor-scales.lesson-2-natural-all-roots",
    title: "Natural Minor From Every Root",
    prerequisites: ["minor-scales.lesson-1-natural-formula"],
    evidence: ["construct", "translate", "diagnose", "apply"],
    tags: ["minor-scale", "natural-minor", "12-pitch-classes", "spelling", "one-letter-each", "construction"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 48,
  },
  {
    ...phase3Shared,
    id: "minor-scales.lesson-3-harmonic-minor",
    title: "Harmonic Minor",
    prerequisites: ["minor-scales.lesson-2-natural-all-roots"],
    evidence: ["construct", "identify", "transform", "apply", "diagnose"],
    tags: ["minor-scale", "harmonic-minor", "raised-7", "leading-tone", "augmented-second", "dominant"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 48,
  },
  {
    ...phase3Shared,
    id: "minor-scales.lesson-4-melodic-minor",
    title: "Melodic Minor",
    prerequisites: ["minor-scales.lesson-3-harmonic-minor"],
    evidence: ["construct", "identify", "transform", "apply", "diagnose"],
    tags: ["minor-scale", "melodic-minor", "raised-6", "raised-7", "ascending", "descending", "classical"],
    conceptualUnderstanding: 5,
    acquisitionRoundSize: 48,
  },
  {
    ...phase3Shared,
    id: "minor-scales.lesson-5-instant-recall",
    title: "Minor Scale Instant Recall Drill",
    prerequisites: ["minor-scales.lesson-4-melodic-minor"],
    evidence: ["construct", "identify", "transform", "diagnose", "apply"],
    tags: ["minor-scale", "natural-minor", "harmonic-minor", "melodic-minor", "automaticity", "12-pitch-classes", "distributed-retrieval", "spelling", "mixed-practice"],
    conceptualUnderstanding: 4,
    acquisitionRoundSize: 60,
  },
]);

export const SKILL_BY_ID = new Map(SKILLS.map((skill) => [skill.id, skill]));
