import { type PhaseNumber } from "../curriculum/index.js";
import { evaluateCheckpoint, nextCheckpointCompetency, type AssessmentEvaluation, type PhaseCheckpointDefinition } from "./checkpoints.js";
export declare function checkpointDefinition(phase: PhaseNumber): PhaseCheckpointDefinition | undefined;
export declare function allCheckpointDefinitions(): PhaseCheckpointDefinition[];
export declare function placementPrerequisitePhases(targetPhase: PhaseNumber): PhaseNumber[];
export declare function placementDefinition(targetPhase: PhaseNumber): PhaseCheckpointDefinition;
export declare function recommendStartingPhase(targetPhase: PhaseNumber, evaluation: AssessmentEvaluation): PhaseNumber;
export declare function phaseCoreReady(phase: PhaseNumber, readySkillIds: ReadonlySet<string>): boolean;
export { evaluateCheckpoint, nextCheckpointCompetency };
export type { AssessmentEvaluation, AssessmentKind, AssessmentResponseMode, CompetencyAssessment, CompetencyDefinition, DiagnosticItemResult, PhaseCheckpointDefinition, } from "./checkpoints.js";
