import type { LessonContent } from "./types.js";

export const PHASE2_MAJOR_SCALE_LESSONS: readonly LessonContent[] = Object.freeze([
  {
    skillId: "major-scales.lesson-1-formula",
    title: "Major Scale Formula",
    teachingSteps: [
      {
        id: "scale-tonic-definition",
        title: "Scale, root, and tonic",
        body: "A scale is an ordered set of notes arranged around a home note. In this phase, the starting home note is the root of the scale; in key/scale language it is also called the tonic, or scale degree 1.",
        workedExample: "In D major, D is the root, the tonic, and degree 1.",
        expectation: "understand",
        visual: { kind: "piano", data: { highlighted: ["D"] } },
      },
      {
        id: "whole-half-definition",
        title: "Whole step and half step",
        body: "A half step is the distance to the very next piano key, including black keys. A whole step equals two half steps. E→F and B→C are half steps even though both notes are white keys.",
        workedExample: "C→C♯ = half step. C→D = whole step. E→F = half step.",
        expectation: "understand",
        visual: { kind: "piano", data: { highlighted: ["C", "C#", "D", "E", "F"] } },
      },
      {
        id: "major-formula",
        title: "The major-scale formula",
        body: "Every ascending major scale follows the same step pattern: W-W-H-W-W-W-H. The half steps occur between degrees 3→4 and 7→1 at the octave.",
        workedExample: "Start on C: C→D W, D→E W, E→F H, F→G W, G→A W, A→B W, B→C H.",
        expectation: "know-instantly",
        visual: { kind: "scale", data: { notes: ["C", "D", "E", "F", "G", "A", "B"] } },
      },
      {
        id: "interval-connection",
        title: "This is Phase 1 put in a row",
        body: "The formula is not a random code. Measured from the tonic, major-scale degrees make the Phase 1 intervals P1, M2, M3, P4, P5, M6, M7, then P8 at the octave.",
        workedExample: "In C major: C→E is M3, C→G is P5, and C→B is M7. Those are the same interval relationships you already learned.",
        expectation: "understand",
        visual: { kind: "interval", data: { root: "C", target: "G", label: "degree 5 = P5" } },
      },
      {
        id: "apply-d-major",
        title: "Apply it immediately — D major",
        body: "Start on D and move W-W-H-W-W-W-H. Keep the letters in order D-E-F-G-A-B-C, then use accidentals to make each distance correct.",
        workedExample: "D→E W, E→F♯ W, F♯→G H, G→A W, A→B W, B→C♯ W, C♯→D H. D major = D E F♯ G A B C♯.",
        expectation: "understand",
        visual: { kind: "piano", data: { highlighted: ["D", "E", "F#", "G", "A", "B", "C#"] } },
      },
      {
        id: "formula-payoff",
        title: "Why learn the formula",
        body: "The formula is your backup method. You should understand how to rebuild a scale from it even after the scale itself becomes memorized.",
        workedExample: "If you forget E♭ major later, W-W-H-W-W-W-H lets you reconstruct it instead of guessing.",
        payoff: "Major scales will become the note pool for later diatonic chords, Roman numerals, transposition, and improvisation.",
        expectation: "know-instantly",
      },
    ],
  },
  {
    skillId: "major-scales.lesson-2-degree-names",
    title: "Scale Degree Names",
    teachingSteps: [
      {
        id: "degree-definition",
        title: "What a scale degree is",
        body: "A scale degree is a note's numbered position inside a scale. Major scales have seven different degrees, numbered 1 through 7; the octave repeats degree 1.",
        workedExample: "In C major, C=1, D=2, E=3, F=4, G=5, A=6, B=7.",
        expectation: "understand",
        visual: { kind: "scale", data: { notes: ["C", "D", "E", "F", "G", "A", "B"] } },
      },
      {
        id: "tonic-supertonic",
        title: "1 Tonic · 2 Supertonic",
        body: "Tonic means degree 1, the home note of the key. Supertonic means degree 2, the scale note directly above the tonic.",
        workedExample: "In D major, D is the Tonic (1) and E is the Supertonic (2).",
        expectation: "know-instantly",
      },
      {
        id: "mediant-subdominant",
        title: "3 Mediant · 4 Subdominant",
        body: "Mediant is degree 3. Subdominant is degree 4. You need the names and numbers; you do not need to memorize where the words came from.",
        workedExample: "In D major, F♯ is the Mediant (3) and G is the Subdominant (4).",
        expectation: "know-instantly",
      },
      {
        id: "dominant-submediant",
        title: "5 Dominant · 6 Submediant",
        body: "Dominant is degree 5. Submediant is degree 6. The dominant will become especially important when you learn chords and harmonic function.",
        workedExample: "In D major, A is the Dominant (5) and B is the Submediant (6).",
        expectation: "know-instantly",
      },
      {
        id: "leading-tone",
        title: "7 Leading Tone",
        body: "Leading Tone is degree 7 in a major scale. It sits a half step below the tonic and strongly points back toward degree 1.",
        workedExample: "In D major, C♯ is the Leading Tone (7), one half step below D.",
        expectation: "know-instantly",
        visual: { kind: "piano", data: { highlighted: ["C#", "D"] } },
      },
      {
        id: "degree-priority",
        title: "What should become automatic",
        body: "Know the degree numbers 1–7 instantly and become fluent with all seven names. Tonic (1), Subdominant (4), Dominant (5), and Leading Tone (7) are especially important because later harmony constantly refers to them.",
        workedExample: "If you hear 'the dominant of A major,' your brain should immediately translate that to degree 5, then E.",
        payoff: "Scale degrees let you think in musical roles instead of memorizing unrelated note names in every key.",
        expectation: "know-instantly",
      },
    ],
  },
  {
    skillId: "major-scales.lesson-3-build-all-roots",
    title: "Building the Major Scale From Every Root",
    teachingSteps: [
      {
        id: "twelve-pitch-classes",
        title: "All 12 pitch classes",
        body: "The piano repeats 12 pitch classes before the octave. Phase 2 balances practice across all 12, so easy keys like C, G, and D cannot crowd out the black-key roots.",
        workedExample: "The 12 practice roots are C, D♭, D, E♭, E, F, F♯, G, A♭, A, B♭, and B, with conventional enharmonic spellings added where useful.",
        expectation: "understand",
        visual: { kind: "piano", data: { highlighted: ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"] } },
      },
      {
        id: "one-letter-each",
        title: "Use each letter name once",
        body: "A seven-note diatonic major scale uses each musical letter exactly once before the tonic repeats. First choose the next letter; then choose the accidental that makes the W/H distance correct.",
        workedExample: "D major must be D-E-F♯-G-A-B-C♯. Writing G♭ instead of F♯ would skip F and use G twice.",
        expectation: "understand",
      },
      {
        id: "enharmonic-definition",
        title: "Enharmonic does not mean interchangeable spelling",
        body: "Enharmonic notes share a piano key but have different written names. A root pitch class can therefore support more than one correctly spelled major key, and the chosen tonic name controls the rest of the scale spelling.",
        workedExample: "F♯ major and G♭ major sound on the same piano keys, but their written note names are different.",
        expectation: "understand",
      },
      {
        id: "fsharp-major",
        title: "F♯ major",
        body: "Starting from F♯, keep the letters F-G-A-B-C-D-E and apply the major pattern. That produces a sharp spelling.",
        workedExample: "F♯ major = F♯ G♯ A♯ B C♯ D♯ E♯. E♯ is correct because degree 7 must use the letter E and sit a half step below F♯.",
        expectation: "know-instantly",
        visual: { kind: "scale", data: { notes: ["F♯", "G♯", "A♯", "B", "C♯", "D♯", "E♯"] } },
      },
      {
        id: "gflat-major",
        title: "G♭ major",
        body: "Starting from G♭, keep the letters G-A-B-C-D-E-F and apply the same major pattern. The piano pitches match F♯ major, but the spelling follows G♭ as tonic.",
        workedExample: "G♭ major = G♭ A♭ B♭ C♭ D♭ E♭ F. C♭ is correct here; replacing it with B would repeat B and skip C.",
        expectation: "know-instantly",
        visual: { kind: "scale", data: { notes: ["G♭", "A♭", "B♭", "C♭", "D♭", "E♭", "F"] } },
      },
      {
        id: "supported-key-spellings",
        title: "12 sounds, a few useful written alternatives",
        body: "Practice is balanced by the 12 underlying pitch classes, while also supporting the conventional enharmonic major-key spellings C♯/D♭, F♯/G♭, and B/C♭. Uncommon names such as D♯ major are theoretically derivable but are not separate default memorization targets here because they require awkward double-sharp spellings.",
        workedExample: "C♯ major = C♯ D♯ E♯ F♯ G♯ A♯ B♯. D♭ major = D♭ E♭ F G♭ A♭ B♭ C.",
        expectation: "understand",
      },
      {
        id: "build-payoff",
        title: "Build accurately before you memorize",
        body: "Construction proves you understand the system. Practice now rotates full scales, missing notes, requested degrees, and note→degree questions across the entire keyboard.",
        workedExample: "If asked for degree 6 of E♭ major, build or recall E♭ F G A♭ B♭ C D: degree 6 is C.",
        payoff: "Correct spelling matters because later chords and Roman numerals depend on which scale degree a note actually is.",
        expectation: "know-instantly",
      },
    ],
  },
  {
    skillId: "major-scales.lesson-4-instant-recall",
    title: "Major Scale Instant Recall Drill",
    teachingSteps: [
      {
        id: "recall-goal",
        title: "Move from calculating to recalling",
        body: "At first, W-W-H-W-W-W-H is supposed to help you calculate. The long-term goal is to see a major key and recall its notes accurately without rebuilding every step one at a time.",
        workedExample: "A major should eventually arrive as A-B-C♯-D-E-F♯-G♯, not as seven separate keyboard calculations.",
        expectation: "know-instantly",
      },
      {
        id: "construction-stays-underneath",
        title: "Do not throw away the formula",
        body: "Automatic recall sits on top of understanding. If memory fails, use the formula and the one-letter-per-degree rule to derive the answer, then let later retrieval strengthen that key again.",
        workedExample: "Forget A♭ major? Rebuild A♭-B♭-C-D♭-E♭-F-G, then retrieve it again later without the scaffold.",
        expectation: "understand",
      },
      {
        id: "distributed-retrieval",
        title: "Why the keys keep coming back",
        body: "One successful round is not permanent mastery. The app distributes retrieval across sessions and keeps READY major-scale material eligible for later review until delayed evidence becomes durable.",
        workedExample: "You may recall B major today, see it mixed with other keys later, and meet it again in a delayed review rather than drilling it once and abandoning it.",
        expectation: "understand",
      },
      {
        id: "balanced-roots",
        title: "Every pitch class gets meaningful coverage",
        body: "Recall rounds rotate all 12 pitch classes instead of overusing C/G/D. Full-scale spelling, individual degrees, missing notes, and reverse degree questions are interleaved so one memorized question format cannot carry you.",
        workedExample: "A round can move from D♭ major to A major to F♯ major to E♭ major, then ask for a single degree instead of another full scale.",
        expectation: "know-instantly",
      },
      {
        id: "phase1-stays-alive",
        title: "Intervals still matter",
        body: "Phase 2 occasionally pulls useful Phase 1 interval questions back into the session. Major scales contain M2, M3, P4, P5, M6, M7, and the octave relationship from their tonic, so interval fluency keeps supporting scale fluency.",
        workedExample: "Degree 5 is a P5 above the tonic. Degree 7 is an M7 above the tonic.",
        expectation: "understand",
      },
      {
        id: "recall-payoff",
        title: "Why instant major scales matter",
        body: "When the notes of a key are automatic, later theory stops spending mental bandwidth on basic lookup. You can focus on chords, function, transposition, and musical choices instead.",
        workedExample: "If E major is instantly E-F♯-G♯-A-B-C♯-D♯, building its diatonic chords later becomes much faster.",
        payoff: "This is the scale equivalent of memorizing multiplication facts before doing algebra.",
        expectation: "know-instantly",
      },
    ],
  },
]);
